
modLoader = "javafml" #mandatory
loaderVersion = "[44,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId = "chineseworkshop" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Chinese Work Shop" #mandatory
#logoFile="chineseworkshop.png" #optional
authors = "cnlimiter, CityOfSkyTCD" #optional

description = '''

'''
[[dependencies.chineseworkshop]]
    modId="kiwi"
    mandatory=true
    versionRange="[9,)"
    ordering="BEFORE"
    side="BOTH"
